Biblioteca Pandas
### Aula 03

In [25]:
import pandas as pd 
import numpy as np

In [ ]:
quantidade_produtos = [3,5,6,10]
precos_produtos = [10,5,7,100]

array_produtos = np.array(quantidade_produtos)
array_precos = np.array(precos_produtos)

faturamento = array_produtos * array_precos
print(faturamento)

In [ ]:
quantidade_produtos = [3,5,6,10]
precos_produtos = [10,5,7,100]
nomes_produtos =["Pastel", "Caçulinha", "Refrigerante", "Combos"]

array_produtos = np.array(quantidade_produtos)
array_precos = np.array(precos_produtos)

faturamento = array_produtos * array_precos
for nome,preco in zip(nomes_produtos,faturamento):
    print(f"{nome} : {preco:.2f}")

### Exercício de fixação 
- Criar uma lista de irá possuir 10 nomes de produtos.
- Criar uma lista que irá possuir o preço de custo(atacado).
- Criar uma lista que irá possuir o preço de venda(varejo).
- Ao final, exibir o lucro obtido em cada produto.

In [ ]:
nomes_produtos =["Samsung A71", "Samsung S21", "Samsung J7 prime", "Iphone XR", "Xiaomi mi 11", "Redmi note 10 pro", "Samsung Z fold 4", "Iphone 11", "Samsung A33", "Samsung tab A7"]
precos_produtos = [600, 1500, 400, 750, 1100, 700, 3800, 1100, 700, 600]
custo_produtos =  [200, 500, 100, 350, 300, 250, 1000, 500, 250, 200]

array_precos = np.array(precos_produtos)
array_custo = np.array(custo_produtos)
faturamento = array_precos - array_custo
for nome,preco in zip(nomes_produtos,faturamento):
    print(f"Lucro de produtos vendidos: {nome} = {preco:.2f}")
faturamento_total = np.sum(faturamento)
print(f"Seu lucro total foi de {faturamento_total:.2f} ")

## Pandas

In [32]:
df = pd.read_csv(r".\data\dataset_aula1_numpy_pandas.csv") #ignora barras invertidas
df.head() #Por padão exibe 5 primeiras informações
df.tail() #Exibe as 5 últimas informações

    id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
35           36  Usinagem          68.47          36.87            87      0
36           37  Inspeção          75.62          30.78           125      1
37           38  Usinagem          78.50          36.39            90      0
38           39  Montagem          76.19          36.54           111      1
39           40  Montagem          68.64          34.88           102      0

In [ ]:
#Mostra as dimensões da tabela
df.shape

(40, 6)

In [34]:
# Mostra as colunas da tabela
df.columns

Index(['id_registro', 'setor', 'temperatura_c', 'tempo_ciclo_s',
       'producao_dia', 'falha'],
      dtype='object')

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_registro    40 non-null     int64
 1   setor          40 non-null     object
 2   temperatura_c  40 non-null     float64
 3   tempo_ciclo_s  40 non-null     float64
 4   producao_dia   40 non-null     int64
 5   falha          40 non-null     int64
dtypes: float64(2), int64(3), object(1)
memory usage: 2.0+ KB

In [ ]:
df.duplicated().sum() #contar valores duplicados

np.int64(0)

In [ ]:
#Contar valores nulos
df.isna().sum()

id_registro      0
setor            0
temperatura_c    0
tempo_ciclo_s    0
producao_dia     0
falha            0
dtype: int64

In [ ]:
df.describe() #std = Desvio padrão (com valores absurdos chamam de outliers)
            #quartis 25% 50% 75%

       id_registro  temperatura_c  tempo_ciclo_s  producao_dia      falha
count    40.000000      40.000000      40.000000     40.000000  40.000000
mean     20.500000      72.525750      35.103250    116.400000   0.300000
std      11.690452       5.923691       3.918479     26.071696   0.464095
min       1.000000      60.310000      27.200000     80.000000   0.000000
25%      10.750000      68.597500      32.580000     92.750000   0.000000
50%      20.500000      73.425000      34.960000    111.000000   0.000000
75%      30.250000      76.310000      36.925000    136.750000   1.000000
max      40.000000      85.020000      47.450000    159.000000   1.000000